### PR TITLE
[RFC] Draft of Appium support

### PR DESCRIPTION
**Pull request by abourget**
/cc @sclevine

### CODE REVIEW

**Comment by abourget** [comment]
Reworked based off your initial design.

Up for review.

If you'd want to stub out what'll be needed for tests, I'd appreciate. Or just the basic frame for the different components.

I'm going to start implementing the selectors and actions now.

**Comment by abourget** [comment]
I'm having a hard time understanding the interactions between `selection.go`, `selectable.go`, `internal/element/repository.go`,.. I feel I'm going to need to duplicate much of the selectable and selection things, and not much reusability.

Can we open `newSelection` up a little ? since the Selection object is already public, having a function to assign its internal `elements` could prove useful, otherwise I can't use it at all from `appium/`.

**Comment by abourget** [comment]
We have `pageSession`, `selectionSession`, now `deviceSession` and another `selectionSession` in appium.. 

Any reason all those couldn't be an `*api.Session` ? since it is the only implementation we have ?

**Comment by sclevine** [comment]
Do what you need to do to access those methods for now - I'll figure something out that doesn't expose too much of the `Selection` after work.

Those interfaces exist so that the `api.Session` can be mocked out in test with the most minimal mock possible for the object under test. They could be consolidated for now if they are identical.

**Comment by abourget** [comment]
as I can see, most of the `selectable` recursive features are probably not needed, unless we support CSS, right ?  Does it make sense to call something like `page.AllByXPath("...").FirstByLabel("asdf").Find("tr")` ?

what nesting is allowed ?

In the case of appium, CSS is not supported to query nodes, and the UI Automation and UI Automators have their own sort of language to select nodes, so I'm not sure it's meaningful to come back in Go and continue the selection with recursive functions.  If we can assert this is true, then it would simplify the selectable/selection case, where we could only have `.FindByClass()`, `.FindA11yID()`, `.FindAndroid()`, `.FindiOS()` and `FindByXPath()` directly on the `Device` object.

I'm going to prototype such a thing (and we can add the selection/selectable after if needed).

**Comment by sclevine** [comment]
All nesting is allowed. When CSS selectors are chained, they are merged before an actual lookup occurs. When different kinds of selectors are merged, `api.Element`s are found recursively. See [here](https://code.google.com/p/selenium/wiki/JsonWireProtocol#POST_/session/:sessionId/element/:id/element).

As the native mobile app UIs are serializable into XML, I assume they work the same way. I'll try to figure out a way for you to add selector types to the `appium.Selection` and `appium.Device` without adding them to the corresponding `agouti` structs tonight.

**Comment by abourget** [comment]
Can you based off your work from my branch ?  You can break it all you
want, I'll pick it up where you leave it afterwards.

**Comment by sclevine** [comment]
Will do :)

**Comment by sclevine** [comment]
Hi @abourget,

I had less time to work on this today than I thought I would. Stay with your implementation of `NewSelection` for now -- I may rename it to `BuildSelection` in the future and give it godoc noting that it's for internal use only. Some other notes:
- Consider moving the `TouchAction` complexity into the `appium` package. The `api/mobile` package should map endpoints to methods and have virtually no other responsibilities. Use the `api` package as an example.
- Note that you'll need to test code before I can merge it. I strongly encourage test driving (TDD), and I'm a little concerned about the work so far not containing any tests. I would be happy to merge this pull request in parts (before it supports the entire Appium API), but those parts will need to be fully tested. I would be happy to go into more detail about TDD if you'd like.
- Consume dependencies using interfaces so that they can be mocked out. I noticed that you switched the individual session interfaces to `*mobile.Session`. This will make `Device` and `Selection` methods in the `appium` package quite hard to test. Consider embedding the `*agouti.Page` and `*agouti.Selection` as interfaces as well.

I'll definitely have more time to work on your branch over the weekend.

**Comment by abourget** [comment]
@sclevine I'm studying https://github.com/sclevine/agouti/blob/master/api/element_test.go#L46-L67 and wondering what was the design around that ?

* why run the `element.Send()` in `BeforeEach()` and redo it in `Context()..It()` ?
* why not have all the expects be run right after the call to `element.Send` in `BeforeEach`, transforming that `BeforeEach` in an `It` block, and taking out the `It()` from inside the `ItShouldMakeAnElementRequest()` ? the latter only doing the expect calls for deduplication ?

The only reason I see for that is if you want to continue doing the `Expect()` calls of `ItShouldMakeAn...` even if one of them fail.  So that would make resurface the lack of subtlety we find in the standard Go `testing` library about `Error` and `FailNow`.. when we can log an error, but continue the test.  Is that the case ?

**Comment by sclevine** [comment]
Hi @abourget, happy to clarify:

1) Consider the relevant portions of the `Describe`:
```go
Describe("#Send", func() {
	var result string

	BeforeEach(func() {
		bus.SendCall.Result = `"some result"`
		err = element.Send("endpoint", "method", "body", &result)
	})

	...

	Context("when the bus indicates a failure", func() {
		It("should return an error", func() {
			bus.SendCall.Err = errors.New("some error")
			err := element.Send("endpoint", "method", "body", &result)
			Expect(err).To(MatchError("some error"))
		})
	})
})
```
The first `element.Send` is called in order to make assertions in the other `It` blocks (`...`). The second `element.Send` is called after the error state is set on the `bus`. This tests the error case. This does mean that there is an extraneous call to `element.Send` for that particular test. The block could be re-written as:
```go
Describe("#Send", func() {
	Context("when the bus does not indicate a failure", func() {
		var result string

		BeforeEach(func() {
			bus.SendCall.Result = `"some result"`
			err = element.Send("endpoint", "method", "body", &result)
		})
		...
	})

	Context("when the bus indicates a failure", func() {
		It("should return an error", func() {
			bus.SendCall.Err = errors.New("some error")
			err := element.Send("endpoint", "method", "body", &result)
			Expect(err).To(MatchError("some error"))
		})
	})
})
```
This would prevent the extra call, but the extra call doesn't cost very much, and the extra block doesn't add much to the readability of the test.

2) This would reduce the granularity of the tests (and as you mention, stop the other tests from running). That could be fine. I don't feel very strongly about this, and I don't love shared behavior, so if you want to structure your tests that way, feel free to. I don't like how those tests keep a globally shared `err error` anyways.

**Comment by abourget** [comment]
ok, good, thanks.

**Comment by abourget** [comment]
Regarding https://github.com/sclevine/agouti/pull/44#issuecomment-77512447 ...

when I try to make those as interfaces, I get whirled into a big refactor of the selectable, selection and things that are private to `agouti`.. so I made them like that for now.. hopefully we can find a way to open things in agouti a bit more, or even better, move some of the interfaces to internal, so both top-level webdrivers can use them. Obviously, using the structs limits testing.. I hope we can fix that together.

I definitely want to write tests for anything new before it merges, I'm still digesting the larger picture. I'm going to give TDD another spin on this :)

I'll move the `TouchAction` stuff to `appium/`..

**Comment by abourget** [comment]
What do you think of https://github.com/abourget/agouti/commit/2c354d7f622e3d39c9aad9f1852708da6392eb1c ?

**Comment by sclevine** [comment]
I like to think of interfaces as consumer-side contracts that define exactly how one part of an application uses something it depends on. What trouble are you running into to exactly?

The `selectable` struct in `agouti` lives at the top level because it has to return `agouti.Selection`s. If it moved down, there would be a dependency cycle between `agouti` and whatever package it moved into. I would lean towards duplicating things for now. If the issue is that you can't access the internal `selectors` in an `agouti.Selection` to create your new `appium.Selection`s, it may be possible to use refection to copy those unexported fields out. Definitely not the cleanest solution, but it could work for now.

**Comment by abourget** [comment]
Ok, I moved TouchAction, wrote a couple of tests on top of this newly rebased branch.  Thanks for all your hard work and refactors :) Tests are a lot easier to read now :) heheh

**Comment by abourget** [comment]
I'm having to make tough choices.  Appium can switch from native to web in a swift.. so we really need those `Find()` CSS selection calls.. it would make sense for a `.Find()` call to return an `agouti.Selection`, just like in the `agouti` package, but I'm not sure it'd make sense to have the `FindByA11yID()` call return an `agouti.Selection`, since its session over there wouldn't be a `mobileSession`.  At the same time, the selection machinery is pretty abstracted from the `mobile` things, but you couldn't chain a `FindByA11yID()` (or other mobile-specific selectors) if we did so.. So I feel I need to wrap it into a `appium.Selection`.  But then, if you're developing a web and mobile suite, it's really annoying, because you can't reuse some helpers that you write got `agouti` with your `appium` suite.

I'm not sure what I mean is clear.  I'm going to be on IRC tonight to brainstorm and try things.

**Comment by sclevine** [comment]
This makes sense to me. I suspect you'll want to put a number of other methods (besides `Find-` methods) on `appium.Selection`. Any `api/mobile` method that is implemented on `mobile.Element` or takes a `mobile.Element` as an argument should have a method on `appium.Selection` and not a method on `appium.Device` that takes an `appium.Selection`. Thus, I would override all of the `agouti.selectable` methods to return an `appium.Selection`. If your using Appium, you'll only need to refer to a `*appium.Selection` in your helper methods. If you really need to use both, you can define an interface that accepts an intersection of their methods and write your helper method using that.

**Comment by sclevine** [comment]
More concisely: Override all of the `agouti.selectable` methods so that you cannot end up with a `*agouti.Selection` without manually extracting it from the `appium.Selection`. Keep the behavior of the overridden methods the same. Throw an error from `Find()` when it is used in a context where CSS selectors are invalid. Aside from that, the `*appium.Selection` methods will be a superset of the `*agouti.Selection` methods, so you should never need an `*agouti.Selection` when using `appium`.

**Comment by abourget** [comment]
I was wondering, after seeing those heavy duplication in functionalities, methods and tests, if it wouldn't be better to have the appium support directly in the `agouti` package.. reusing the Selection methods completely, making them available on selectables but yielding errors automatically when not useable (or letting a server reply with an error when not appium), offering a distinct `Device` struct aside the `Page` struct, with added functionalities and support for TouchAction..

I'm okay with contining with the current model.. maybe we merge later if we find it makes sense. I was wondering, as I've been mostly arranging code around package walls.. perhaps I we're trying to apply patterns from Python and Ruby where they just subclass dynamically.  Maybe there's something more idiomatic in Go to achieve such things ?

**Comment by sclevine** [comment]
I would like to avoid `agouti.Page` and `agouti.Selection` becoming wide interfaces with methods that a large portion of users won't use and that won't work with most of the WebDrivers. I also don't see this involving very much duplication, outside of the 15 one-line `selectable` methods that will need to point back to their `agouti` versions.

I'm not borrowing this pattern from Python or Ruby. Embedding is just a means to an end here -- we want the set of methods on `*agouti.Selection` and `*agout.Page` to be easily accessible to users of both packages, but we don't a number of those methods to get in the way of regular WebDriver users.

An alternative would be for the `appium` package to provide methods that take a `*agouti.Page` and/or `*agouti.Selection` as arguments. This could be considered more idiomatic Go. For example:
`appium.Tap(selection)`. But it makes `appium` seem "second class" compared to the other WebDrivers. I would consider this pattern if you were strongly in support of it.

But, exactly as you say, we can make this decision later if it makes sense.

**Comment by abourget** [comment]
I just pushed more stuff in here.  There's still a lot of duplication. The element, the FindBy* tests, on device, on selection. And as I continue, I need to copy more and more stuff.

Perhaps the Session could be a shared session? directly in api.Session, and supporting everything we need ? maybe at least this would simplify things.

I'm okay doing it all, especially because it keeps things simple for the users.. but it's going to be a daunting task reconciling or refactoring all of that! but.. you got IntelliJ right ? :) so perhaps you can do it somewhat magically :P

**Comment by sclevine** [comment]
Let me think on this a little bit. The fact that Appium provides extensions to WebElement does make this a bit harder. Pulling in `ElementRepository` won't help, because it depends on interfaces that return `*api.Element`s.

**Comment by sclevine** [comment]
For now, feel free to merge `api.Session` and `mobile.Session` as well as `api.Element` and `mobile.Element` (and get rid of the `api/mobile` package). If you could implement the Appium methods on an `*Appium` object in a field called `Appium` on `api.Session` and `api.Element` (and make this field `nil` by default), it would keep those methods separate enough for me.

**Comment by sclevine** [comment]
To clarify:
- `*api.AppiumSession` gets the methods that are currently on `*mobile.Session`.
- `api.Session` has an `Appium` field that is initialized to a `*api.AppiumSession` for Appium
- `*api.AppiumElement` gets the methods that are currently on `*mobile.Element` (without `GetElement` or `GetElements`, only the few extra Appium methods)
- `api.Element` has an `Appium` field that is initialized to a `*api.AppiumElement` for Appium
- The `appium` package stays separate, but you can reuse much more of the `agouti` code

I refactored `agouti.Page` to use a single session last night. For now, when you create a `*Device`, you should be able to grab that session and set a `*AppiumSession` on it with something like `page.Session().Appium = *api.AppiumSession{Session: page.Session()}`.

**Comment by sclevine** [comment]
After more thought, a less complex alternative to the above would be to keep the `mobile` package and define all of the methods directly on it. These methods could take an `Element` or `Session` interface that's compatible with a `*api.Element` or `*api.Session` as an argument. It would be simple, easy to test, and keep the separation between the WebDriver Wire Protocol and the mobile extensions to it.
Ex.
```go
package mobile
...
func InstallApp(session Session, appPath string) error
```

**Comment by sclevine** [comment]
Actually, it would likely be just as easy to test in this case if you skipped the interface:
```go
package mobile
...
func InstallApp(session *api.Session, appPath string) error {
...
}
```
There is already a pattern in `agouti.Selection` for type-asserting `element.Element` into `*api.Element`, and you could do that in `appium.Selection` as well.

**Comment by sclevine** [comment]
I rebased against master and put some more work on a branch [here](https://github.com/sclevine/agouti/tree/abourget-new). I came up with a pretty simple solution that should get rid of most of the `Selection`/`Element` duplication: embed an `agouti.Page` in an `appium.Device`, but don't introduce an `appium.Selection`. Instead, define methods on `appium.Device` that take an `agouti.Selection`. Same pattern applies for `mobile.Session` -- don't introduce a `mobile.Element`, and instead define methods on `mobile.Session` that take an `api.Element`.

We can introduce two exported `agouti.Selection` methods to support this: `Selectors() Selectors` (which you can use to lookup `api.Element`s in your `appium.Device` using an `element.Repository`) and `FindByAppium(selectorType appium.Selector, selectors string) *Selection` (which users can use to generate `agouti.Selection`s that have Appium-specific selectors in them).

I also put some work into the `TouchActions` stuff. Let me know what you think! I hope this addresses your concerns about the original proposed architecture. It should eliminate almost all of the duplication you were concerned about.

**Comment by abourget** [comment]
Ok cool.. I'll have a look and I'll be continuing the work this week.

Thanks a lot ! :-)

**Comment by abourget** [comment]
so you removed a bunch of the appium-specific `Find-` methods.. they are to call the underlying `FindForAppium()` for each of their specific usage ?  That's a good idea.. will keep things simpler. We should try to use that sort of pattern as much as we can. Have functionalities that support other higher layers. Could even be named something other than "FindForAppium".. as its generic and simply catches any find strategy. I like it :)

**Comment by abourget** [comment]
way better, the creation of the `TouchAction` each time..

**Comment by abourget** [comment]
FindForAppium makes it difficult to chain things.

Why don't we put all the Find* methods directly on the Selection ?  they wouldn't yield anything if not used with an Appium server ?  that would add three finders: `FindByA11yID`, `FindByAndroidUI` and `FindByiOSUI` or something.. we probably don't even need many All() and First() derivatives.. as FindByA11yID should yield only and always one result.  The other Android/iOSUI use a special string'd language that can do many things, even go as far as click on items in there. Maybe `Find` isn't even the prefix we need. It could probably be `QueryiOSUI()` and be available without chaining, strictly on a Device ?

**Comment by sclevine** [comment]
Notice that I completely got rid of `appium.Selection`. You should have no trouble chaining those calls as `FindForAppium` will return a `*agouti.Selection` that has a `FindForAppium` method. We could call it something more generic (`FindOther`?) if you'd like. Ex.
```go
device.FindOther(appium.IOSUI, "something").FindOther(appium.A11y, "something else")
```

Are you sure those methods don't need chaining? My understanding is that the native UIs can be serialized into XML such that elements have subelements. If the `/session/:sessionID/element/:elementID/elements` endpoint will take those selector types, then we should support chaining (because the API does). Even if A11y identifiers are unique, you should still be able to selection them out of an existing selection.

**Comment by abourget** [comment]
ok, let's have: `FindBy(strategy target.Type, selector string)`.. so we'd move the `target.Type` outside of `internal`..   or, we could have a registration strategy, when you load "appium", it registers new "types" as text.. and you could FindBy("text strategy").. that would know how to format itself (like in `internal/target/selector.go`..

Hust having a string as the first FindBy parameter is risky.. as it's exposed to the public.  We'd need to at least make the parameter discoverable, by having it typed. That'd be good enough.. especially since resource IDs are queries with FindByID() ... those would be slightly second-level, but functional and chainable.

I've pushed fixes to your rebased branch that make all tests pass (haven't run the integration tests)... but it,s going in the right direction I think.. Thanks for refactoring those things.

**Comment by sclevine** [comment]
Sounds good.

We could make the function:
```go
FindBy(strategy SelectorType, selector string)
```
where `SelectorType` is an interface that `const` selector types on both `agouti` and `appium` satisfy.

**Comment by abourget** [comment]
This PR has been open for a while.. and we've been using it for mobile and desktop for a little while.  It's not full or complete by whatever means.. but do you think it could be updated to fit the latest agouti, and merged in ? even though it's not feature complete ?  At least this way it would continue to evolve with the rest of agouti.

**Comment by kpashka** [comment]
@abourget +1

**Comment by sclevine** [comment]
Thanks for all of your hard work! I'm sure these changes will be useful to a ton of people.

I'm not opposed at all. I would love to ship these changes and get feedback on them. Would you like to rebase this branch against `master`, or would you like me to? Also, feel free PR an Appium section for agouti.org to the `gh-pages` branch.

I just moved to Michigan, so it may take me a few days to review this and merge it in.

**Comment by abourget** [comment]
Ok, so if I rebase on top of master, we can check out how to merge ?

**Comment by sclevine** [comment]
Or allow me to rebase it. I didn't want to re-write your commit history without asking.

I'm pretty busy right now, but I'll review the changes again when I have an opportunity.

**Comment by abourget** [comment]
I did some merge, not sure everything makes sense..

Maybe it'd be better to rebase indeed... but at least the resolutions are in here.

Keep me posted on progress :) thanks a lot !

**Comment by abourget** [comment]
If I rebase, can we try to advance the case of this merge?! :)

**Comment by abourget** [comment]
Ok, we rebased on latest `master` and fixed tests.

It'd be great to have that merged once and for all, and to have people starting to use and fiddle with it !

We also implemented WebDriver endpoints regarding timeouts that weren't exposed before.

**Comment by Etienne42** [comment]
Tests pass locally, and when looking at travis logs there are no tests failing, but travis `build failed` anyway..

**Comment by sclevine** [comment]
Looks great! I may make a few small changes later, but I'd be happy to merge this now.

Thanks for the contributions!

**Pull request closed without merging**
